@baseApiEndpoint = https://localhost:5001/api

# Get all students
GET {{ baseApiEndpoint }}/students

###
GET {{ baseApiEndpoint }}/students/eafd9639-ea8c-41ba-8f40-9bddb6a2d1eb

###
POST {{ baseApiEndpoint }}/students
Content-Type: application/json 

{
   "firstName": "Joao",
   "lastName": "Mane",
   "dateOfBirth": "2006-06-23",
   "email": "joaopedromane23@gmail.com",
   "mobile": "967248025",
   "avatarURL": "https://robohash.org/JoaoMane",
   "gender": {
     "id": "33ea5b86-cf03-44e9-8882-1da2f7b262a6"
   }
}



###
GET {{ baseApiEndpoint }}/genders

###
PUT {{ baseApiEndpoint }}/students/a8ee04d3-07e9-4ef8-89ed-89bbb4876261
Content-Type: application/json

{
    "firstName": "Not César anymore",
    "lastName": "Mane",
    "dateOfBirth": "2017-01-07T01:47:27.0407597",
    "email": "Cristiano500x0567035@hotmail.com",
    "mobile": "222801161",
     "gender": {
      "id": "75b29bf0-3931-48a4-97ba-070d08dc6417"
    }
}

### 
DELETE {{ baseApiEndpoint }}/students/f45c5885-de6c-3407-3985-a012d0ee7f09

###

