@baseApiEndpoint = https://localhost:5001/api

# Get all students
GET {{baseApiEndpoint}}/students

###
GET @{{baseApiEndpoint}}//students/Id

###
POST {{baseApiEndpoint}}/students
Content-Type: application/json

{

}

###


