@baseApiEndpoint = https://localhost:5001/api

# Get all students
GET {{baseApiEndpoint}}/students

###
GET {{baseApiEndpoint}}/students/aa89e6b1-6ef2-897a-19df-b21af38d2c6a

###
POST {{baseApiEndpoint}}/students
Content-Type: application/json

{

}

###


